### PR TITLE
Add Constructor<T> into ServiceIdentifier<T>

### PR DESCRIPTION
**Pull request by thynson**
Extending `ServiceIdentifier<T>` to accept `Constructor<T>`(which is `<T> { prototype: T}`)

If this change is accepted, constructor of abstract class can be used as service identifier and can also be binded to a concret implementation.

```
// Declare interface as below
@injectable()
abstract class MyServiceInterface { void f(); }

class MyService extends MyServiceInterface { /*...*/ }

// Inject as below
class MyBusiness {
  constructor(@inject(MyServiceInterface) x: MyServiceInterface) {
    /*...*/
  }
}
```
And such way should be more easier than injecting an interface, which need to define a symbol for it.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] My change requires a change to the type definitions.
- [x] I have updated the type definitions accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by remojansen** [comment]
Thanks for this PR there is a few things I need to ask.

```
type ServiceIdentifier<T> = (string|Symbol|Newable<T>|Constructor<T>);
```

I think the names are very similar maybe will confuse users that will wonder what is the difference between a `Newable` and a `Constructor`. Is `Newable` needed? If both are needed should `Constructor` be renamed to Abstract?

**Comment by thynson** [comment]
You are right. Actually `{ prototype: T}` also match a normal constructor. So `Newable<T>` may not be needed. I'm not sure if I should remove `Newable<T>` when I made that patch, as that would breaks something in the hell.

**Comment by thynson** [comment]
Okay I come up an idea that make `Newable<T>` extended from `Constructor<T>`. And seems all the test passed.

**Comment by thynson** [comment]
Have you looked at the amended patch? I believe it's reasonable enough to merge. :)

**Comment by remojansen** [comment]
Hi @thynson sorry I want to write a unit test and document this before merging I will do it at some point this week. Will let you know if I have any problems. Thanks!

**Comment by thynson** [comment]
@remojansen Thanks for you hard working.

**Comment by remojansen** [comment]
I'm closing this PR because this project is about to be deprecated. We have managed to auto-generate the type definitions. The progress can be follow at https://github.com/inversify/InversifyJS/issues/363

**Pull request closed without merging**
